name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    #   - uses: webfactory/ssh-agent@v0.7.0
    #     with:
    #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy Website
        uses: appleboy/ssh-action@v1.0.0
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: cd ${{ secrets.WORK_DIR }} && git checkout main && git pull
