name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set SSH key
        run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            cat >>~/.ssh/config <<END
            Host website
              HostName ${{ secrets.HOST }}
              User $${{ secrets.USERNAME }}
              Port $${{ secrets.PORT }}
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
            END
      - name: SSH to server and pull
        run: ssh -v website "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && exit"
